feat(myhpi): add info bit protobuf
HPI-de/hpi-cloud-apis pull request #7
Opened 2019-07-30 20:40 UTC by marcelgarus

**Fixes: #6**

**Checklist**

- [x] Commit messages follow conventionalcommits.org

**Changes**

2019-07-30 20:44 UTC, JonasWanke requested changes
The service definition is still missing.

2019-07-30 20:44 UTC, JonasWanke commented on hpi/cloud/myhpi/v1test/info_bit.proto
> +// A bit of information to show the user on the MyHPI screen.
This is too focused on the android app, please use a more generic description

2019-07-30 20:44 UTC, JonasWanke commented on hpi/cloud/myhpi/v1test/info_bit.proto
> +package hpi.cloud.news.v1test;
Copy + Paste...

2019-07-30 20:44 UTC, JonasWanke commented on hpi/cloud/myhpi/v1test/info_bit.proto
> +  string text = 3;
Maybe `description` would be a better name?

2019-07-31 07:17 UTC, marcelgarus commented
> The service definition is still missing.

What's that about?

2019-07-31 18:05 UTC, JonasWanke commented
> > The service definition is still missing.
> 
> What's that about?

Right now, only the data wrappers are defined. We still need a service (like [NewsService](https://github.com/HPI-de/hpi-cloud-apis/blob/dev/hpi/cloud/news/v1test/news_service.proto)) to list all methods available on the server

2019-08-10 10:56 UTC, closed without merging